import type { Metadata } from "next";
import { Alegreya_SC,Lemon,Encode_Sans_Semi_Condensed,Merienda} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/footer";
import Header from "@/components/Header/header";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "sonner";
const alegreyaSc = Alegreya_SC({
  variable: "--font-alegreya-sc",
  subsets: ['latin'],
  style: 'normal',
  weight: ['400', '500', '700'],
});
const lemon = Lemon({
  variable: "--font-lemon",
  subsets: ['latin'],
  style: 'normal',
  weight: ['400'],
});
const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ['latin'],
  style: 'normal',
  weight: ["300" , "400" ,"500" , "600" ,"700" ,"800" ,"900" ],
});
const encodeSansSemiCondensed = Encode_Sans_Semi_Condensed({
  variable: "--font-encode-sans-semi-condensed",
  subsets: ['latin'],
  style: 'normal',
  weight: ['400'],
});



export const metadata: Metadata = {
  title: "NovelNook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${alegreyaSc.variable} ${lemon.variable} ${merienda.variable} ${encodeSansSemiCondensed.variable} antialiased bg-[#F2F0D2]`}
      >
        <Header/>
        {children}
        <Footer/>
        <Toaster/>
      </body>
      </AuthProvider>
    </html>
  );
}
