import type { Metadata } from "next";
import { Geist, Geist_Mono,Alegreya_SC,Lemon,Encode_Sans_Semi_Condensed} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/footer";
import Header from "@/components/Header/header";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const alegreyaSc = Alegreya_SC({
  variable: "--font-alegreya-sc",
  subsets: ['latin'],
  style: 'normal',
  weight: ['400', '500', '700'],
});
const lemon = Lemon({
  variable: "--font-lemon",
  subsets: ['latin'],
  style: 'normal',
  weight: ['400'],
});
const encodeSansSemiCondensed = Encode_Sans_Semi_Condensed({
  variable: "--font-encode-sans-semi-condensed",
  subsets: ['latin'],
  style: 'normal',
  weight: ['400'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${alegreyaSc.variable} ${lemon.variable} ${encodeSansSemiCondensed.variable} antialiased bg-[#F2F0D2]`}
      >
        <Header/>
        {children}
        <Footer/>
        <Toaster/>
      </body>
      </AuthProvider>
    </html>
  );
}
